import io.reactivex.Flowable;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {

    public static void main(String[] args) {
        Flowable.fromArray("Hello", " ", "world", "!")
                .subscribe(System.out::print);
    }

}
