/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;

public class ApplicationTest {
    @Test public void testAppHasAGreeting() {
        Application classUnderTest = new Application();
    }
}
